version: '2'
services:
  flyway:
    image: boxfuse/flyway:5
    volumes:
      - ./db/conf:/flyway/conf
      - ./db/migrations:/flyway/sql
      - ./db/sample-data:/flyway/sample-data
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
