name: tso
channels:
  - defaults
dependencies:
    - astropy
    - numpy=1.13.*
    - pytest
    - pandas
    - pip:
        - deap==1.2.2
        - mysql-connector-python
        - astroplan
        - requests
